### ISSUE TITLE
Add a completed projects section

### ISSUE THREAD

**Issue by orobor0s** [CodeWithAloha/website#33]
To differentiate past projects from current ones, need to answer the questions:
- Is this a section that will be a part of the end of March release?
- What projects should be included in this section? (Second Chances, Holo Holo)

**Comment by avenmia** [comment]
Since completion is hard to define for a project, we can add statuses to the project cards on the website instead. Some examples could be:
* Active - People are actively working on the project
* Inactive - People are not currently working on the project
