### ISSUE TITLE
[task] list sponsors of codewithaloha

### ISSUE THREAD

**Issue by tyliec** [CodeWithAloha/website#59]
# Description

We need a section to list our sponsors. As a requirement for letting us use certain meeting spaces (BoxJelly & Entrepreneur Sandbox), we need to give an acknowledgement to the organizations that let us meet there.

Previous Sponsors Section:

![Image](https://github.com/CodeWithAloha/website/assets/15609358/c825cc86-b31e-4464-9e38-a29158bebb40)

Links:
- https://www.htdc.org/
- https://www.theboxjelly.com/
- https://sandboxhawaii.org/
- https://hubcoworkinghi.com/

**Comment by TaigaChang** [comment]
I am starting to work on this. This is my first issue so I might make some mistakes.

**Comment by tyliec** [comment]
> I am starting to work on this. This is my first issue so I might make some mistakes.

Feel free to reach out if you need any help. GitHub notifications are a black hole, so pinging one of us on Slack is probably your best bet :)
